name: bimmer-builder

services:
  mongo:
    image: mongo:8.0
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - bimmer-builder

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - bimmer-builder
    ports:
      - 5000:5000
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - bimmer-builder
    ports:
      - 5173:5173
    command: npm run dev -- --host
    depends_on:
      - api

volumes:
  mongo_data:
networks:
  bimmer-builder:
    driver: bridge
